version: '3.7'

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob:1.12.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: ./cron.env
    deploy:
      placement:
        constraints:
          - node.role == manager
