version: '3.7'

networks:
  internal:
  reverse:
    external: true

volumes:
  web:
  db:

services:
  nextcloud:
    image: nextcloud:28.0.1
    volumes:
      - web:/var/www/html
    networks:
      - internal
      - reverse
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=reverse'
        - 'traefik.http.services.cloud.loadBalancer.server.port=80'
        - 'traefik.http.middlewares.cloud.headers.sslHost=cloud.gsri.team'
        - 'traefik.http.middlewares.cloud.headers.sslRedirect=true'
        - 'traefik.http.middlewares.cloud.headers.sslForceHost=true'
        - 'traefik.http.middlewares.cloud.headers.stsSeconds=31536000'
        - 'traefik.http.middlewares.cloud.headers.stsIncludeSubdomains=true'
        - 'traefik.http.middlewares.cloud.headers.forceStsHeader=true'
        - 'traefik.http.routers.cloud.entrypoints=https'
        - 'traefik.http.routers.cloud.rule=Host(`cloud.gsri.team`)'
        - 'traefik.http.routers.cloud.middlewares=cloud@docker'
        - 'traefik.http.routers.cloud.service=cloud'
        - 'traefik.http.routers.cloud.tls.options=secure@file'
        - 'traefik.http.routers.cloud.tls.certResolver=gandi'
        - 'traefik.http.routers.cloud_unsecure.entrypoints=http'
        - 'traefik.http.routers.cloud_unsecure.rule=Host(`cloud.gsri.team`)'
        - 'traefik.http.routers.cloud_unsecure.middlewares=cloud@docker'
        - 'traefik.http.routers.cloud_unsecure.service=cloud'

  db:
    image: mariadb:10.6.16
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal

  cron:
    image: nextcloud:28.0.1
    command: /usr/local/bin/php /var/www/html/cron.php
    user: '33'
    volumes:
      - web:/var/www/html
    networks:
      - internal
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=*/5 * * * *"
        - "swarm.cronjob.skip-running=true"
      replicas: 0
      restart_policy:
        condition: none
