name: Stack deployment workflow

on:
  workflow_call:
    inputs:
      compose:
        type: string
        required: true
        description: Path to the docker-compose file to deploy
      stack:
        type: string
        required: true
        description: Name of the docker stack to deploy

env:
  STACK_VERSION: ${{ github.run_id }}

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Checkout source files
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - run: docker stack deploy --prune --compose-file ${{ inputs.compose }} ${{ inputs.stack }}
        name: Deploy Docker Swarm stack
