name: Deploy admin

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "stacks/admin/**"

jobs:
  build:
    uses: ./.github/workflows/_deploy.yaml
    with:
      stack: admin
      compose: stacks/admin/docker-compose.yaml
