name: Deploy cloud

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "stacks/cloud/**"

jobs:
  build:
    uses: ./.github/workflows/_deploy.yaml
    with:
      stack: cloud
      compose: stacks/cloud/docker-compose.yaml
