name: Deploy reverse

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "stacks/reverse/**"

jobs:
  build:
    uses: ./.github/workflows/_deploy.yaml
    with:
      stack: reverse
      compose: stacks/reverse/docker-compose.yaml
